version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  init_env:
    docker:
      - image: continuumio/miniconda3:22.11.1

    steps:
      - checkout
      # create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install make curl -y
            make set_env
            make install_kube_deps
            conda info --envs
      - run:
          name: run lint
          command: |
            conda info --envs
            source activate dash_avocado
            pip install pylint pylint_flask
            make lint 

  create_set_infra:
    docker:
      - image: continuumio/miniconda3:22.11.1

    steps:
      - checkout
      # create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install make
            make create-cluster


workflows:
  default:
    jobs:
      #- init_env
      #- aws-ecr/build-and-push-image:
      #    context: aws-dev
      #    create-repo: false
      #    dockerfile: Dockerfile
      #    path: .
      #    repo: capstone
      #    tag: "green"
      #    requires:
      #          - init_env
      - create_set_infra