version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    
    working_directory:  ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install make curl -y
            make install
            conda info --envs
      - run:
          name: run lint
          command: |
            conda info --envs
            source activate dashboard.yml
            make lint 


workflows:
  default:
    jobs:
      - build        
