version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install make curl -y
            make install
            conda info --envs
      - run:
          name: run lint
          command: |
            conda info --envs
            source activate dash_avocado
            pip install pylint pylint_flask
            make lint 


workflows:
  default:
    jobs:
      - build        
