apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plotly-dash
  template:
    metadata:
      labels:
        app: plotly-dash
    spec:
      containers:
        - name: back-end
          image: 530835307231.dkr.ecr.us-east-1.amazonaws.com/capstone:blue
          ports:
            - containerPort: 8080